### PR TITLE
add NdpPlanResolver

### PR DESCRIPTION
**Pull request by Jutao-liu**

### CODE REVIEW

**Review by xulilililili — CHANGES_REQUESTED** [review]
```
((ndpStatusInfoMap.size() > 0) ? ndpStatusInfoMap.entrySet()
                    .stream()
                    .map(s -> s.getValue().getDatanodeHost() + " -> " + s.getKey())
                    .collect(Collectors.joining(", ")) : ""));
```
 When there are too many cluster nodes, a large number of logs are printed, which is difficult to locate. You are advised to set the number of logs by setting Limit.

**Review by xulilililili — CHANGES_REQUESTED** [review]
Partial pushdown does not support Agg, you need to make a check.

**Review by xulilililili — CHANGES_REQUESTED** [review]
`tableScanOp.getNumChild() == 1`
 If this condition is not met, the system does not push down but no log is recorded,

**Review by xulilililili — CHANGES_REQUESTED** [review]
The FilterProjectDispatcher class name does not match its actual function.

**Comment by Jutao-liu** [comment]
#2

**Review by xulilililili — APPROVED** [review]

**Comment by Jutao-liu** [comment]
> ```
> ((ndpStatusInfoMap.size() > 0) ? ndpStatusInfoMap.entrySet()
>                     .stream()
>                     .map(s -> s.getValue().getDatanodeHost() + " -> " + s.getKey())
>                     .collect(Collectors.joining(", ")) : ""));
> ```
> 
> When there are too many cluster nodes, a large number of logs are printed, which is difficult to locate. You are advised to set the number of logs by setting Limit.

Good advice. Completed modification

**Comment by Jutao-liu** [comment]
> ```
> ((ndpStatusInfoMap.size() > 0) ? ndpStatusInfoMap.entrySet()
>                     .stream()
>                     .map(s -> s.getValue().getDatanodeHost() + " -> " + s.getKey())
>                     .collect(Collectors.joining(", ")) : ""));
> ```
> 
> When there are too many cluster nodes, a large number of logs are printed, which is difficult to locate. You are advised to set the number of logs by setting Limit.

Good advice. Completed modification

**Comment by Jutao-liu** [comment]
> 

Good advice. Completed modification

**Comment by Jutao-liu** [comment]
> `tableScanOp.getNumChild() == 1` If this condition is not met, the system does not push down but no log is recorded,

Good advice. Completed modification

**Comment by Jutao-liu** [comment]
> The FilterProjectDispatcher class name does not match its actual function.

Good advice. Completed modification

**Comment by xulilililili** [comment]
> > The FilterProjectDispatcher class name does not match its actual function.
> 
> Good advice. Completed modification

thank you ~tao

**Pull request merged**
